#!/bin/bash

DEST_DIR="$HOME/dev/dotfiles"


# zsh
rm -rf "$DEST_DIR/.zshrc"
yes | \cp -rf "$HOME/.zprezto/runcoms/zshrc" "$DEST_DIR/.zshrc"
rm -rf "$DEST_DIR/.zpreztorc"
yes | \cp -rf "$HOME/.zprezto/runcoms/zpreztorc" "$DEST_DIR/.zpreztorc"

# scripts
rm -rf "$DEST_DIR/scripts"
yes | \cp -rf "$HOME/scripts/" "$DEST_DIR"

# fonts
rm -rf "$DEST_DIR/.fonts"
yes | \cp -rf "$HOME/.fonts/" "$DEST_DIR"
