#!/bin/bash

player_status=$(playerctl status 2> /dev/null)
# player_type=$(playerctl metadata 2> /dev/null)
# ARTIST=$(playerctl metadata artist |& tail -1)
TITLE=$(playerctl metadata title |& tail -1)

if [ "$player_status" = "Playing" ]; then
    echo " $TITLE"
elif [ "$player_status" = "Paused" ]; then
    echo " $TITLE"
else
    echo "X"
fi



